[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
firebase-bom = "33.5.0"
recyclerview = "1.3.2"
glide = "4.16.0"
gson = "2.10.1"
lifecycleLivedataCore = "2.10.0"
roomCommonJvm = "2.8.4"
roomRuntime = "2.8.4"
roomCompiler = "2.8.4"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version = "23.0.0" }
firebase-auth-google = { group = "com.google.firebase", name = "firebase-auth", version = "23.0.0" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version = "25.0.0" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }


recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-core = { group = "androidx.lifecycle", name = "lifecycle-livedata-core", version.ref = "lifecycleLivedataCore" }
room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
firebase-google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
